#!/sbin/sh

OUTFD=/proc/self/fd/$2
ZIPFILE="$3"

ui_print() {
    if $BOOTMODE; then
        echo "$1"
    else
        echo -e "ui_print $1\nui_print" >>$OUTFD
    fi
}

abort() {
    local i=$?
    ui_print "$1"
    exit $i
}
BOOTMODE=false
ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true
$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true

ui_print "====================================="
ui_print "     此包由刷写包自动生成"
ui_print " Automatically generated for Flash pack"
ui_print "         Author: 亦魔/Yemon "
ui_print "====================================="
ui_print "警告：恢复包仅限自己使用"
ui_print "warning only for yourself"
rm -rf /tmp/aaaa/
mkdir -p /tmp/aaaa/
unzip -o $ZIPFILE -d /tmp/aaaa/

device_serialno=abcdef
boot_serialno=abcdef

if [[ $(getprop ro.serialno) == "$device_serialno" ]] || [[ $(getprop ro.boot.serialno) == "$boot_serialno" ]]; then
    ui_print "- flashing modem_bak.img to modem partition..."
    dd if=/tmp/aaaa/modem_bak.img of=/dev/block/by-name/modem || abort "flash modem failed"
    ui_print "- flash modem done."

    ui_print "- flashing modemst1_bak.img to modemst1 partition..."
    dd if=/tmp/aaaa/modemst1_bak.img of=/dev/block/by-name/modemst1 || abort "flash modemst1 failed"
    ui_print "- flash modemst1 done."

    ui_print "- flashing modemst2_bak.img to modemst2 partition..."
    dd if=/tmp/aaaa/modemst2_bak.img of=/dev/block/by-name/modemst2 || abort "flash modemst2 failed"
    ui_print "- flash modemst2 done."

    ui_print "- flashing fsc_bak.img to fsg partition..."
    dd if=/tmp/aaaa/fsc_bak.img of=/dev/block/by-name/fsg || abort "flash fsc failed"
    ui_print "- flash fsc done."

    ui_print "- flashing fsg_bak.img to fsg partition..."
    dd if=/tmp/aaaa/fsg_bak.img of=/dev/block/by-name/fsg || abort "flash fsg failed"
    ui_print "- flash fsg done."
else
    ui_print "机型序列号校验失败，请不要使用转发或使用他人生成的恢复基带包"
    ui_print "如果你确定这是自己的，有可能因为二次刷机导致校验产品序列号失败"
    ui_print "修复方法：在REC或Termux执行 \'getprop ro.serialno\' 获取正确的序列号，修改此包的update-binary文件第34-35行"
    ui_print "Model serial number verification failed. Please do not use forwarding or recovery baseband packages generated by others."
    ui_print "If you are sure this is your own device, the failure to verify the product serial number might be due to a second flash."
    ui_print "To fix it: Run \'getprop ro.serialno\' in REC or Termux to obtain the correct serial number, and then modify lines 34-35 in the update-binary file of this package."
    exit 1
fi

exit 0